RELATIVE_CWD_SCRIPT_PATH=$0
ABSOLUTE_SCRIPT_PATH=$(realpath $RELATIVE_CWD_SCRIPT_PATH)
ABSOLUTE_SCRIPTS_DIRECTORY_PATH=$(dirname $ABSOLUTE_SCRIPT_PATH)
ABSOLUTE_SCRIPT_GLOBALS_ENV_PATH="$ABSOLUTE_SCRIPTS_DIRECTORY_PATH/SCRIPTS_GLOBAL.env"
source $ABSOLUTE_SCRIPT_GLOBALS_ENV_PATH

SOURCE_FILE_PATH="./source/main.c"
OUTPUT_EXECUTABLE_PATH="${OUTPUT_DIRECTORY_PATH}/mechanism_cc"
CLANG_OPTION_ARGUMENTS=$1

if [ ! -d "$OUTPUT_DIRECTORY_PATH" ]; then
    mkdir $OUTPUT_DIRECTORY_PATH
fi
infer run -- \
    clang $CLANG_OPTION_ARGUMENTS \
    -o $OUTPUT_EXECUTABLE_PATH \
    $SOURCE_FILE_PATH
